FROM python:3.11-slim
WORKDIR /code
COPY dags ./dags
COPY dataset ./dataset
COPY model ./model
COPY ./docker_setup/train/requirements.txt ./
RUN pip install -r requirements.txt
CMD ["cp", "-r", ".", "/source_code"]